main: aliuly\helper\Main
api: 
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
load: POSTWORLD
depend: [SimpleAuth]

name: SimpleAuthHelper
description: Simplifies the way people authenticate to servers
version: 1.3.0dev2
author: aliuly

commands:
  chpwd:
    description: "Change password"
    usage: "/chpwd <old_password>"
    permission: simpleauthhelper.command.chpwd
    aliases: [passwd]
  resetpwd:
    description: "Reset password"
    usage: "/resetpwd <player>"
    permission: simpleauthhelper.command.resetpwd
    aliases: [resetpw]

permissions:
  simpleauthhelper.command.chpwd:
    default: true
    description: "Allow users to change passwords"
  simpleauthhelper.command.resetpwd:
    default: op
    description: "Allow ops to reset other's passwords"
